Supports user authentication and better error handling
* Use getallheaders() to fetch request headers so that fields like
"Authorization" can be forwarded
* remove urldecode when creating $request_url so that if csurl contains
encoded part it won't be decoded by mistake
* If curl_exec failed, send back plain text error message. E.g., Curl
error: SSL certificate problem: unable to get local issuer certificate.